// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

function fibonacci() {
  let a = 1,
    b = 0,
    temp;
  let loop = 4000000;

  let fiboSum = 0;

  while (b <= 4000000) {
    temp = a;
    a = a + b;
    b = temp;
    loop--;
    console.log("fibonacciNumbers.js:18", b);
    if (b % 2 === 0) {
      fiboSum = fiboSum + b;
      console.log(" >>>> ", b, fiboSum);
    }
  }
  console.log("fibonacci", fiboSum);
  return b;
}

fibonacci();
